spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eddiepengdenvren/config-repo
          username: 136351717@qq.com
          password: 159xiaoai
  rabbitmq:
#      host: 10.253.1.19
      host: 192.168.1.22
      port: 5672
      username: guest
      password: guest
#      username: digibig
#      password: digibig
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"